# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/ChewTools/SER/ChewToolsExporter/ExporterUI_002.ui'
#
# Created: Tue Feb 13 11:45:54 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 360)
        self.ExporterTab = QtWidgets.QTabWidget(MainWindow)
        self.ExporterTab.setGeometry(QtCore.QRect(0, 0, 801, 351))
        self.ExporterTab.setObjectName("ExporterTab")
        self.MotionTab = QtWidgets.QWidget()
        self.MotionTab.setObjectName("MotionTab")
        self.motionInput = QtWidgets.QPlainTextEdit(self.MotionTab)
        self.motionInput.setGeometry(QtCore.QRect(90, 110, 641, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.motionInput.setFont(font)
        self.motionInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.motionInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.motionInput.setPlainText("")
        self.motionInput.setObjectName("motionInput")
        self.motionNameDisplay = QtWidgets.QLabel(self.MotionTab)
        self.motionNameDisplay.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.motionNameDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.motionNameDisplay.setObjectName("motionNameDisplay")
        self.exportBox = QtWidgets.QLabel(self.MotionTab)
        self.exportBox.setGeometry(QtCore.QRect(30, 80, 51, 20))
        self.exportBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exportBox.setObjectName("exportBox")
        self.exportPathInput = QtWidgets.QPlainTextEdit(self.MotionTab)
        self.exportPathInput.setGeometry(QtCore.QRect(90, 80, 641, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportPathInput.sizePolicy().hasHeightForWidth())
        self.exportPathInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exportPathInput.setFont(font)
        self.exportPathInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.exportPathInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.exportPathInput.setPlainText("")
        self.exportPathInput.setObjectName("exportPathInput")
        self.animExportButton = QtWidgets.QPushButton(self.MotionTab)
        self.animExportButton.setGeometry(QtCore.QRect(90, 270, 641, 20))
        self.animExportButton.setObjectName("animExportButton")
        self.charaNameDisplay = QtWidgets.QLabel(self.MotionTab)
        self.charaNameDisplay.setGeometry(QtCore.QRect(40, 20, 41, 20))
        self.charaNameDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.charaNameDisplay.setObjectName("charaNameDisplay")
        self.charaNameInput = QtWidgets.QPlainTextEdit(self.MotionTab)
        self.charaNameInput.setGeometry(QtCore.QRect(90, 20, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.charaNameInput.setFont(font)
        self.charaNameInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.charaNameInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.charaNameInput.setPlainText("")
        self.charaNameInput.setObjectName("charaNameInput")
        self.ingameButton1 = QtWidgets.QRadioButton(self.MotionTab)
        self.ingameButton1.setGeometry(QtCore.QRect(130, 140, 86, 16))
        self.ingameButton1.setChecked(True)
        self.ingameButton1.setObjectName("ingameButton1")
        self.ingameButton2 = QtWidgets.QRadioButton(self.MotionTab)
        self.ingameButton2.setGeometry(QtCore.QRect(270, 140, 101, 16))
        self.ingameButton2.setObjectName("ingameButton2")
        self.weapNameDisplay = QtWidgets.QLabel(self.MotionTab)
        self.weapNameDisplay.setGeometry(QtCore.QRect(40, 50, 41, 20))
        self.weapNameDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weapNameDisplay.setObjectName("weapNameDisplay")
        self.weapNameInput = QtWidgets.QPlainTextEdit(self.MotionTab)
        self.weapNameInput.setGeometry(QtCore.QRect(90, 50, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.weapNameInput.setFont(font)
        self.weapNameInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.weapNameInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.weapNameInput.setPlainText("")
        self.weapNameInput.setObjectName("weapNameInput")
        self.ExporterTab.addTab(self.MotionTab, "")
        self.ModelTab = QtWidgets.QWidget()
        self.ModelTab.setObjectName("ModelTab")
        self.charaNameInput_2 = QtWidgets.QPlainTextEdit(self.ModelTab)
        self.charaNameInput_2.setGeometry(QtCore.QRect(90, 20, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.charaNameInput_2.setFont(font)
        self.charaNameInput_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.charaNameInput_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.charaNameInput_2.setPlainText("")
        self.charaNameInput_2.setObjectName("charaNameInput_2")
        self.charaNameDisplay_2 = QtWidgets.QLabel(self.ModelTab)
        self.charaNameDisplay_2.setGeometry(QtCore.QRect(40, 20, 41, 20))
        self.charaNameDisplay_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.charaNameDisplay_2.setObjectName("charaNameDisplay_2")
        self.exportPathInput_2 = QtWidgets.QPlainTextEdit(self.ModelTab)
        self.exportPathInput_2.setGeometry(QtCore.QRect(90, 50, 571, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportPathInput_2.sizePolicy().hasHeightForWidth())
        self.exportPathInput_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exportPathInput_2.setFont(font)
        self.exportPathInput_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.exportPathInput_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.exportPathInput_2.setPlainText("")
        self.exportPathInput_2.setObjectName("exportPathInput_2")
        self.exportBox_2 = QtWidgets.QLabel(self.ModelTab)
        self.exportBox_2.setGeometry(QtCore.QRect(30, 50, 51, 20))
        self.exportBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exportBox_2.setObjectName("exportBox_2")
        self.modelExportButton = QtWidgets.QPushButton(self.ModelTab)
        self.modelExportButton.setGeometry(QtCore.QRect(90, 270, 571, 20))
        self.modelExportButton.setObjectName("modelExportButton")
        self.ExporterTab.addTab(self.ModelTab, "")

        self.retranslateUi(MainWindow)
        self.ExporterTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "SER 出力ツール", None, -1))
        self.motionNameDisplay.setText(QtWidgets.QApplication.translate("MainWindow", "モーション名：", None, -1))
        self.exportBox.setText(QtWidgets.QApplication.translate("MainWindow", "出力パス", None, -1))
        self.animExportButton.setText(QtWidgets.QApplication.translate("MainWindow", "出力", None, -1))
        self.charaNameDisplay.setText(QtWidgets.QApplication.translate("MainWindow", "キャラ名", None, -1))
        self.ingameButton1.setText(QtWidgets.QApplication.translate("MainWindow", "モーション", None, -1))
        self.ingameButton2.setText(QtWidgets.QApplication.translate("MainWindow", "カメラ", None, -1))
        self.weapNameDisplay.setText(QtWidgets.QApplication.translate("MainWindow", "武器名", None, -1))
        self.ExporterTab.setTabText(self.ExporterTab.indexOf(self.MotionTab), QtWidgets.QApplication.translate("MainWindow", "モーション出力", None, -1))
        self.charaNameDisplay_2.setText(QtWidgets.QApplication.translate("MainWindow", "キャラ名", None, -1))
        self.exportBox_2.setText(QtWidgets.QApplication.translate("MainWindow", "出力パス", None, -1))
        self.modelExportButton.setText(QtWidgets.QApplication.translate("MainWindow", "出力", None, -1))
        self.ExporterTab.setTabText(self.ExporterTab.indexOf(self.ModelTab), QtWidgets.QApplication.translate("MainWindow", "モデル出力", None, -1))

